LogLevel:  # debug, prod

TelegramTimezone: # Europe/Moscow
TelegramPhone: 
TelegramAppHash:
TelegramAppID: 
TelegramChatID: 

GoogleSheetsServiceAccountCredentialsFile: # google_service_account_credentials.json
GoogleSheetsSpreadsheetID: 
GoogleSheetsSheet: 